#  Forward pass

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы: 
* Deep Learning with PyTorch (2020) Авторы: Eli Stevens, Luca Antiga, Thomas Viehmann 
* https://pytorch.org/docs/stable/generated/torch.matmul.html
* https://machinelearningmastery.com/choose-an-activation-function-for-deep-learning/
* https://machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/
* https://kidger.site/thoughts/jaxtyping/
* https://github.com/patrick-kidger/torchtyping/tree/master

## Задачи для совместного разбора

In [19]:
from torchtyping import TensorType, patch_typeguard
from typeguard import typechecked
import torch as th

Scalar = TensorType[()]
patch_typeguard()

1\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте нейрон с заданными весами `weights` и `bias`. Пропустите вектор `inputs` через нейрон и выведите результат. 

In [20]:
class Neuron:
    def __init__(self, n_features: int, bias: float = 0.0):
        # Создаем атрибуты объекта weights и bias
        self.weights: TensorType[n_features] = th.randn(n_features)
        print(self.weights)
        self.bias: float = bias

    def forward(self, inputs: TensorType["n_features"]) -> Scalar:
        # Реализуем логику нейрона: скалярное произведение + смещение
        return th.dot(inputs, self.weights) + self.bias


In [21]:
import torch as th
inputs = th.tensor([1.0, 2.0, 3.0, 4.0])

In [22]:
neuron = Neuron(4, bias=1.0)
neuron.forward(inputs)


tensor([ 0.4979, -0.8159, -0.9067,  0.8774])


tensor(0.6553)

2\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

In [23]:
class ReLU:
    @typechecked
    def forward(self, inputs: TensorType["n_features"]) -> TensorType["n_features"]:
        # Реализация ReLU: max(0, x)
        return th.clamp(inputs, min=0)

In [30]:
# Создаем матрицу размера (4, 3) из стандартного нормального распределения
matrix = th.randn(4, 3)
print("Исходная матрица:")
print(matrix)

# Применяем ReLU построчно (каждая строка — это n_features)
relu = ReLU()
result = th.stack([relu.forward(matrix[i]) for i in range(matrix.shape[0])])
print("\nПосле ReLU (все отрицательные значения заменены на 0):")
print(result)


Исходная матрица:
tensor([[ 0.5623, -0.9015, -0.1356],
        [-0.5039, -0.6518,  0.8678],
        [-0.8007, -0.1789,  1.8287],
        [ 0.1895,  1.9689,  0.7285]])

После ReLU (все отрицательные значения заменены на 0):
tensor([[0.5623, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.8678],
        [0.0000, 0.0000, 1.8287],
        [0.1895, 1.9689, 0.7285]])


3\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)
где $Y_i$ - правильный ответ для примера $i$, $\hat{Y_i}$ - предсказание модели для примера $i$, $n$ - количество примеров в батче.

In [24]:
class MSELoss:
    @typechecked
    def forward(self, y_pred: TensorType["batch"], y_true: TensorType["batch"]) -> Scalar:
        return (y_pred - y_true).square().mean()

In [25]:
y_pred = th.tensor([1.0, 3.0, 5.0])
y_true = th.tensor([2.0, 3.0, 4.0])

In [26]:
l = MSELoss()
l = l.forward(y_pred, y_true)
l

tensor(0.6667)

## Задачи для самостоятельного решения

### Cоздание полносвязных слоев

<p class="task" id="1"></p>

1\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения) и опциональным вектором смещения. 

$$y = xW^T + b$$

Пропустите вектор `inputs` через слой и выведите результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

- [ ] Проверено на семинаре

In [31]:
class Linear:
    def __init__(self, n_neurons: int, n_features: int, bias: bool = False) -> None:
        self.w = th.randn(n_features, n_neurons)
        self.b = th.randn(n_neurons)

    def forward(self, inputs: TensorType["batch", "feats"]) -> TensorType["batch", "n_neurons"]:
        return inputs @ self.w + self.b
    #return th.mm(inputs, self.w) + self.b

In [32]:
inputs = th.tensor([1.0, 2.0, 3.0, 4.0])
linear = Linear(n_neurons=3, n_features=4, bias=True)
output = linear.forward(inputs)
output

tensor([ 3.3308,  4.8231, -1.5922])

<p class="task" id="2"></p>

2\. Используя решение предыдущей задачи, создайте 2 полносвязных слоя и пропустите тензор `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выберите произвольно, количество нейронов во втором слое выберите так, чтобы результатом прогона являлась матрица `batch_size x 7`. 

- [ ] Проверено на семинаре

In [33]:
batch_size = 5
n_features = 4

l1 = Linear(10, n_features)
l2 = Linear(7, 10)

inputs = th.randn(batch_size, n_features)


In [34]:
y1 = l1.forward(inputs)
y2 = l2.forward(y1)
y2.size()

torch.Size([5, 7])

### Создание функций активации

<p class="task" id="3"></p>

3\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

$$\overrightarrow{x} = (x_1, ..., x_J)$$

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров. Функция должна применяться переданной на вход матрице построчно.

- [ ] Проверено на семинаре

In [35]:
class Softmax:
    def forward(self, inputs: TensorType["batch", "feats"]) -> TensorType["batch", "feats"]:
        # Реализация Softmax с численной стабильностью
        # Вычитаем максимум для избежания переполнения
        exps = th.exp(inputs - th.max(inputs, dim=-1, keepdim=True).values)
        return exps / th.sum(exps, dim=-1, keepdim=True)

In [39]:
# Создаем матрицу размера (4, 3) — выходы линейного слоя для 4 примеров, 3 класса
matrix = th.randn(4, 3)
print("Исходная матрица (логиты):")
print(matrix)

# Применяем Softmax построчно
softmax = Softmax()
probs = softmax.forward(matrix)
print("\nПосле Softmax (вероятности):")
print(probs)

# Проверка: сумма по строкам должна быть равна 1
print("\nСумма вероятностей по строкам (должна быть 1.0):")
print(probs.sum(dim=1))


Исходная матрица (логиты):
tensor([[-0.6273,  1.0757, -0.5612],
        [ 0.9120,  0.9163,  0.1430],
        [ 0.7633, -0.8257,  0.9842],
        [-0.5568,  0.9200, -2.5006]])

После Softmax (вероятности):
tensor([[0.1323, 0.7264, 0.1413],
        [0.4052, 0.4070, 0.1878],
        [0.4079, 0.0833, 0.5088],
        [0.1811, 0.7930, 0.0259]])

Сумма вероятностей по строкам (должна быть 1.0):
tensor([1.0000, 1.0000, 1.0000, 1.0000])


<p class="task" id="4"></p>

4 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создайте матрицу размера 4x3, заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

- [ ] Проверено на семинаре

In [36]:
class ELU:
    def __init__(self, alpha: float) -> None:
        self.alpha = alpha
    
    def forward(self, inputs: TensorType["batch", "feats"]) -> TensorType["batch", "feats"]:
        # Реализация ELU: f(x) = x если x > 0, иначе alpha * (exp(x) - 1)
        return th.where(inputs > 0, inputs, self.alpha * (th.exp(inputs) - 1))

In [40]:
# Создаем матрицу размера (4, 3) из стандартного нормального распределения
matrix = th.randn(4, 3)
print("Исходная матрица:")
print(matrix)

# Применяем ELU с alpha=1.0
elu = ELU(alpha=1.0)
result = elu.forward(matrix)
print("\nПосле ELU (alpha=1.0):")
print(result)

# Проверка: положительные значения не меняются, отрицательные — сжимаются
print("\nПроверка: положительные элементы совпадают с исходными:")
print(th.allclose(result[matrix > 0], matrix[matrix > 0]))
print("Отрицательные элементы теперь в диапазоне (-alpha, 0):")
print(f"min: {result[matrix < 0].min().item():.4f}, max: {result[matrix < 0].max().item():.4f}")


Исходная матрица:
tensor([[ 0.9105,  0.3027, -1.0847],
        [ 2.0714,  0.9117,  0.3213],
        [ 0.4022, -1.5308, -1.2755],
        [-0.6332,  1.1493, -0.6851]])

После ELU (alpha=1.0):
tensor([[ 0.9105,  0.3027, -0.6620],
        [ 2.0714,  0.9117,  0.3213],
        [ 0.4022, -0.7836, -0.7207],
        [-0.4691,  1.1493, -0.4959]])

Проверка: положительные элементы совпадают с исходными:
True
Отрицательные элементы теперь в диапазоне (-alpha, 0):
min: -0.7836, max: -0.4691


### Создание функции потерь

<p class="task" id="5"></p>

5 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь CrossEntropyLoss:

$$y_i = (y_{i,1},...,y_{i,k})$$ 

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

$$ CrossEntropyLoss = \frac{1}{n}\sum_{i=1}^{n}{L_i}$$
где $y_i$ - вектор правильных ответов для примера $i$, $\hat{y_i}$ - вектор предсказаний модели для примера $i$; $k$ - количество классов, $n$ - количество примеров в батче.

Создайте полносвязный слой с 2 нейронами и прогнать через него батч `inputs`. Полученный результат пропустите через функцию активации Softmax. Посчитайте значение функции потерь, трактуя вектор `y` как вектор правильных ответов.

- [ ] Проверено на семинаре

In [42]:
class CrossEntropyLoss:
    def forward(self, y_pred: TensorType["batch", float], y_true: TensorType["batch", int]):
        # Реализация Cross Entropy Loss
        # y_pred - вероятности после softmax (batch, num_classes)
        # y_true - индексы правильных классов (batch,)

        log_probs = th.log(y_pred + 1e-8)  # Добавляем небольшое значение для избежания лог(0)
        # Выбираем log вероятности для правильных классов
        return -th.mean(log_probs[th.arange(y_pred.shape[0]), y_true])

In [ ]:

layer = Linear(n_neurons=2, n_features=n_features)
softmax = Softmax()
ce_loss = CrossEntropyLoss()

logits = layer.forward(inputs)                 # (5, 2) — логиты
probs  = softmax.forward(logits)               # (5, 2) — вероятности

# Вектор правильных ответов (индексы классов 0 или 1)
y = th.tensor([0, 1, 0, 1, 0])

loss = ce_loss.forward(probs, y)

print("Логиты (до Softmax):")
print(logits)
print("\nВероятности (после Softmax):")
print(probs)
print(f"\nПравильные ответы: {y.tolist()}")
print(f"\nCrossEntropyLoss = {loss.item():.6f}")


Логиты (до Softmax):
tensor([[ 2.0326e+00,  2.3711e+00],
        [ 2.0813e+00,  2.1240e+00],
        [ 2.4990e+00,  2.9724e-01],
        [ 2.1275e-03, -1.8288e+00],
        [-1.6390e+00,  8.5478e-01]])

Вероятности (после Softmax):
tensor([[0.4162, 0.5838],
        [0.4893, 0.5107],
        [0.9004, 0.0996],
        [0.8619, 0.1381],
        [0.0763, 0.9237]])

Правильные ответы: [0, 1, 0, 1, 0]

CrossEntropyLoss = 1.241249


<p class="task" id="6"></p>

6 Модифицируйте MSE, добавив L2-регуляризацию.

$$MSE_R = MSE + \lambda\sum_{i=1}^{m}w_i^2$$

где $\lambda$ - коэффициент регуляризации; $w_i$ - веса модели.

- [ ] Проверено на семинаре

In [44]:
class MSERegularized:
    def __init__(self, lambda_: float) -> None:
        self.lambda_ = lambda_

    def data_loss(
            self, 
            y_pred: TensorType["batch"], 
            y_true: TensorType["batch"],
    ) -> Scalar:
        # Подсчет MSE: среднее квадратичное отклонение
        return (y_pred - y_true).square().mean()

    def reg_loss(self, weights: TensorType["batch", 1])  -> Scalar:
        # Подсчет L2 регуляризации: сумма квадратов весов
        return (weights ** 2).sum()

    def forward(
        self, 
        y_pred: TensorType["batch"], 
        y_true: TensorType["batch"], 
        weights: TensorType["batch", 1],
    ) -> Scalar:
        # Полная функция потерь: MSE + lambda * L2_регуляризация
        return self.data_loss(y_pred, y_true) + self.lambda_ * self.reg_loss(weights)

In [ ]:

mse_reg = MSERegularized(lambda_=0.01)

y_pred_reg = th.tensor([2.5, 0.0, 2.0, 8.0])
y_true_reg = th.tensor([3.0, -0.5, 2.0, 7.0])
# Веса модели (форма batch x 1, как требует аннотация типов)
weights = th.tensor([[0.5], [1.2], [-0.8], [2.0]])

data  = mse_reg.data_loss(y_pred_reg, y_true_reg)
reg   = mse_reg.reg_loss(weights)
total = mse_reg.forward(y_pred_reg, y_true_reg, weights)

print(f"MSE (data loss)       = {data.item():.6f}")
print(f"L2 reg loss           = {reg.item():.6f}")
print(f"lambda                = {mse_reg.lambda_}")
print(f"Total MSE_R = MSE + λ·L2 = {total.item():.6f}")
print(f"\nПроверка: {data.item():.6f} + {mse_reg.lambda_}·{reg.item():.6f} = {data.item() + mse_reg.lambda_ * reg.item():.6f}")


MSE (data loss)       = 0.375000
L2 reg loss           = 6.330000
lambda                = 0.01
Total MSE_R = MSE + λ·L2 = 0.438300

Проверка: 0.375000 + 0.01·6.330000 = 0.438300
