# Лекция 1 (часть 2): Введение в работу с PyTorch

__Автор: Сергей Вячеславович Макрушин__ e-mail: SVMakrushin@fa.ru 

Финансовый универсиет, 2021 г. 

При подготовке лекции использованы материалы:
* ...

V 0.5 04.02.2021

## Разделы: <a class="anchor" id="разделы"></a>
* [?Установка PyTorch](#установка)
* [Тензоры и опреации с ними в PyTorch](#тензоры)
    * [Создание тензоров](#создание-тензоров)
    * [Операции с тензорами](#операции-тензоры)    
        * [Арифметические операции и математические функции:](#aрифметические)        
        * [Операции, изменяющие размер тензора](#размер)        
        * [Операции агрегации](#агрегации)        
        * [Матричные операции](#aрифметические)                
-

* [к оглавлению](#разделы)

In [1]:
# загружаем стиль для оформления презентации
from IPython.display import HTML
from urllib.request import urlopen
html = urlopen("file:./lec_v2.css")
HTML(html.read().decode('utf-8'))

## Установка PyTorch <a class="anchor" id="установка"></a>
* [к оглавлению](#разделы)

-----
#### Современные инструменты для создание моделей на основе ИНС

* TensorFlow / Keras 
* PyTorch


TODO: более полный обзор современного "рынка"

## Тензоры и опреации с ними в PyTorch <a class="anchor" id="тензоры"></a>
* [к оглавлению](#разделы)

__Что понимается под тензором в TensorFlow, PyTorch и аналогичных инструментах?__

* <em class="df"></em> __Тензор (в линейной алгербре)__ — объект линейной алгебры, линейно преобразующий элементы одного линейного пространства в элементы другого. Частными случаями тензоров являются скаляры, векторы, билинейные формы и т. п.

* Часто тензор представляют как многомерную таблицу $ d \times d \times \cdots \times d $, заполненную числами - компонентами тензора (где $d$ — размерность векторного пространства, над которым задан тензор, а число размерностей совпадает рангом (валентностью) тензора. В случае ранга 2 запись тензора на письме выглядит как матрица.

* Запись тензора в виде многомерной таблицы возможна __только после выбора базиса (системы координат)__ (кроме скаляров - тензоров размерности 0). Сам тензор как "геометрическая сущность" от выбора базиса не зависит. Это можно наглядно видеть на примере вектора (тензора ранга 1) при смене системы координат: 
    * при смене системы координат __компоненты вектора__ (и в общем случае - тензора) __меняются__ определённым образом.
    * но сам __вектор__ — как "геометрическая сущность", образом которого может быть просто направленный отрезок — __при смене системы координат не изменяется__. Это же относится и к общему случаю - тензору.


* В PyTorch, TensorFlow и  аналогичных библиотеках ключевыми объектами являются __тензоры__, но:
    * __это не настоящие тензоры линейной алгебры__, а просто __многомерные таблицы__. В частности:
        * эти тензоры __не прдедусматривают определение базиса и возможности его изменения__.
    * для тензов (многомерных таблиц) в PyTorch определены различные операции, важные для построения графа потока вычислений для численногомоделирования ИНС и ряда других приложений.
    
* Далее под тензорами мы будем иметь в виду то, что под ними понимается в PyTorch, TensorFlow и других аналогичных библиотеках.
* __Тензоры__ в TensorFlow, PyTorch и аналогичных библиотеках в очень многих аспектах __похожы на массивы NumPy__.
    
<center> 
<img src="./img/ker_5.png" alt=""Тензоры" в TensorFlow и аналогичных инструментах." style="width: 600px;"/><br/>
    <b>"Тензоры" в TensorFlow и аналогичных инструментах.</b>    
</center> 

Тензоры в TensorFlow по логике использования и интерфейсу очень близки к `ndarray` в NumPy.
* тензор размерности 0 - скаляр
* тензор размерности 1 - вектор (одномерный массив)
* тензор размерности 2 - матрица (двухмерный массив массив)
* тензор размерности N - N-мерный массив

In [2]:
import torch
import numpy as np

In [3]:
# Получение версии PyTorch
torch.__version__

'2.10.0+cpu'

---

### Создание тензоров <a class="anchor" id="создание-тензоров"></a>
* [к оглавлению](#разделы)

In [4]:
# В pytorch все основано на операциях с тензорами
# Тензоры могут иметь:
# 0 измерений - скаляры
# 1 измерение - векторы
# 2 измерения - матрицы
# 3, 4, ... измерения - тензоры

# Создание не инициализизированного тензора: torch.empty(size)
# Нужно помнить, что перед использованием такого тензора его обязательно нужно инициализировать!

x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([132099.2500])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[[1.3518e+05, 2.0375e-42, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


In [5]:
# Большинство операций с тензорами очень похожа на опреации с массивами NumPy, но часть имеют небольшие отличия: 
x_np = np.empty((2,2,3))
print(x_np)
# x_np = np.empty(2,2,3) # Ошибка!

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [6]:
# Создание тензора, заполненного случайными значениями (равномерно распредленными в [0, 1]): torch.rand(size)
x = torch.rand(5, 3)
x

tensor([[0.7065, 0.2589, 0.1161],
        [0.5809, 0.6122, 0.9672],
        [0.3289, 0.9784, 0.5026],
        [0.8028, 0.6020, 0.4760],
        [0.1626, 0.7837, 0.4782]])

In [7]:
# Создание тензоров заполненных:
# нулями: 
x = torch.zeros(5, 3)
print(x)
# единицами: 
x = torch.ones(5, 3)
print(x)
# тензор c единицами на главной диагонали:
x = torch.eye(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# определение размера тензора:
x.size()

torch.Size([5, 3])

In [9]:
# для каждого тензора задан тип значений:
print(x.dtype) # тип заданный автоматически

# явное указание типа:
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


<center> 
<img src="./img/lnnp2_types1.png" alt="Типы тензоров в PyTorch и массивов в NumPy" style="width: 600px;"/><br/>
    <b>Типы тензоров в PyTorch и массивов в NumPy</b>    
</center> 

In [10]:
x = torch.Tensor(2, 3) # аналогично torch.empty
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# создание тензора из данных:
x = torch.Tensor([[0.6768, 0.5198, 0.6978], 
                  [0.1581, 0.2027, 0.3723]])
x

tensor([[0.6768, 0.5198, 0.6978],
        [0.1581, 0.2027, 0.3723]])

In [12]:
# создание тензора из данных:
x = torch.tensor([[6, 51, 6],
                  [15, 0, 37]])
print(x, type(x), x.dtype)

x = torch.tensor([[6, 51, 6],
                  [15, 0, 37]], dtype=torch.float64)
print(x, type(x), x.dtype)

tensor([[ 6, 51,  6],
        [15,  0, 37]]) <class 'torch.Tensor'> torch.int64
tensor([[ 6., 51.,  6.],
        [15.,  0., 37.]], dtype=torch.float64) <class 'torch.Tensor'> torch.float64


In [13]:
# создание тензора из массива numpy:
a = np.array([1, 2, 3])
x = torch.from_numpy(a)
x

tensor([1, 2, 3])

In [14]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other

a[0] += 10
print(a)
print(x)

[11  2  3]
tensor([11,  2,  3])


In [15]:
# torch to numpy with .numpy()
# Специфика использования общего массива данных сохраняется!
b = x.numpy()
b

array([11,  2,  3])

In [16]:
# заполнение тензора значениями:
x = torch.Tensor(2, 3)
x.fill_(0.5) # функции, оканчивающиеся на _ меняют значение тензора слева от точки
x

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

Справка по операциям создания тензоров тут: https://pytorch.org/docs/stable/torch.html#creation-ops

---

### Операции с тензорами <a class="anchor" id="операции-тензоры"></a>
* [к оглавлению](#разделы)

#### Арифметические операции и математические функции: <a class="anchor" id="aрифметические"></a>
* [к оглавлению](#разделы)

In [17]:
x = torch.rand(2, 2)
print(f'x:\n {x}\n')
y = torch.rand(2, 2)
print(f'y:\n {y}\n')

# поэлементное сложение:
z = x + y
print(f'z = x + y:\n {z}\n')
z = torch.add(x, y)
print(f'z = torch.add(x,y):\n {z}\n')

x:
 tensor([[0.0365, 0.4502],
        [0.9462, 0.2358]])

y:
 tensor([[0.7443, 0.4583],
        [0.7308, 0.4078]])

z = x + y:
 tensor([[0.7808, 0.9085],
        [1.6770, 0.6436]])

z = torch.add(x,y):
 tensor([[0.7808, 0.9085],
        [1.6770, 0.6436]])



In [18]:
y2 = y.clone().detach() # копирование содержимого тензора в новый тензор
print(f'y2:\n {y2}\n')

# операции "in place" (помещают результат в объект слева от точки) в pytorch оканчиваются на _ :
y2.add_(x)
print(f'y2.add_(x) in place:\n {y2}\n')

y2:
 tensor([[0.7443, 0.4583],
        [0.7308, 0.4078]])

y2.add_(x) in place:
 tensor([[0.7808, 0.9085],
        [1.6770, 0.6436]])



In [19]:
# вычитание:
z = x - y
z = torch.sub(x, y)
print(f'z = torch.sub(x, y):\n {z}\n')

# умножение (поэлементное!):
z = x * y
z = torch.mul(x,y)
print(f'z = torch.mul(x,y):\n {z}\n')

# деление:
z = x / y
z = torch.div(x,y)
print(f'z = torch.div(x,y):\n {z}\n')

z = torch.sub(x, y):
 tensor([[-0.7078, -0.0082],
        [ 0.2155, -0.1720]])

z = torch.mul(x,y):
 tensor([[0.0272, 0.2063],
        [0.6915, 0.0962]])

z = torch.div(x,y):
 tensor([[0.0491, 0.9822],
        [1.2949, 0.5783]])



In [20]:
print(f'x - y:\n {x - y}\n')

z = torch.abs(x - y) # полэлементный рассчет модуля
print(f'z = torch.abs(x - y):\n {z}\n')

z = x - y
z.abs_()
print(f'z.abs_():\n {z}\n')

x - y:
 tensor([[-0.7078, -0.0082],
        [ 0.2155, -0.1720]])

z = torch.abs(x - y):
 tensor([[0.7078, 0.0082],
        [0.2155, 0.1720]])

z.abs_():
 tensor([[0.7078, 0.0082],
        [0.2155, 0.1720]])



In [21]:
torch.cos(x) # поэлементный рассчет cos 
# x.cos_()

tensor([[0.9993, 0.9004],
        [0.5847, 0.9723]])

In [22]:
torch.sigmoid(x) # рассчет сигмоиды
# x.sigmoid_()

tensor([[0.5091, 0.6107],
        [0.7204, 0.5587]])

Справка по математическим опреациям тут: https://pytorch.org/docs/stable/torch.html#math-operations

#### Операции, изменяющие размер тензора: <a class="anchor" id="размер"></a>
* [к оглавлению](#разделы)

In [23]:
# Операции среза (slicing) (работает аналогично NumPy):
x = torch.rand(5,3)
print(x)
print(x[1, 1]) # элемент с индексо 1, 1 (результат: тензор размерности 0!)
print(x[:, 0]) # все строки, столбец 0
print(x[1, :]) # строка 1, все столбцы

tensor([[0.5511, 0.7375, 0.9312],
        [0.6817, 0.0459, 0.8658],
        [0.3091, 0.9893, 0.1806],
        [0.6633, 0.2540, 0.4967],
        [0.9665, 0.7444, 0.6858]])
tensor(0.0459)
tensor([0.5511, 0.6817, 0.3091, 0.6633, 0.9665])
tensor([0.6817, 0.0459, 0.8658])


In [24]:
# тензор размерности 0 (скаляр), все равно остается типом 'torch.Tensor':
print(x[1,1], type(x[1,1])) 

tensor(0.0459) <class 'torch.Tensor'>


In [25]:
# получение самого значения из тензора размерности 0:
print(x[1,1].item())

0.04591524600982666


In [26]:
# итерирование по тензору:
for v in x[1, :]:
    print(v.item())

0.6816701889038086
0.04591524600982666
0.8658356070518494


In [27]:
# Изменение формы тензора (reshape) с помощью torch.view():
x = torch.randn(4, 4) # матрица 4 на 4
print(x, x.size(), '\n')

tensor([[-0.2039,  0.5950, -0.2921,  0.2429],
        [ 0.1622, -0.1940,  1.5692,  0.9087],
        [ 1.0467,  0.3018,  0.7266, -1.3458],
        [ 0.2106,  0.6514, -1.0260,  0.5671]]) torch.Size([4, 4]) 



In [28]:
y = x.view(16) # вектор из 16 компонент
print(y, y.size(), '\n')
z = x.view(2, 2, 4) # тензор 2 на 2 на 4
print(z, z.size(), '\n')

tensor([-0.2039,  0.5950, -0.2921,  0.2429,  0.1622, -0.1940,  1.5692,  0.9087,
         1.0467,  0.3018,  0.7266, -1.3458,  0.2106,  0.6514, -1.0260,  0.5671]) torch.Size([16]) 

tensor([[[-0.2039,  0.5950, -0.2921,  0.2429],
         [ 0.1622, -0.1940,  1.5692,  0.9087]],

        [[ 1.0467,  0.3018,  0.7266, -1.3458],
         [ 0.2106,  0.6514, -1.0260,  0.5671]]]) torch.Size([2, 2, 4]) 



In [29]:
t = x.view(-1, 8)  # размер -1 означает, что размерность этой компоненты будет подобрана автоматически
print(t, t.size())

tensor([[-0.2039,  0.5950, -0.2921,  0.2429,  0.1622, -0.1940,  1.5692,  0.9087],
        [ 1.0467,  0.3018,  0.7266, -1.3458,  0.2106,  0.6514, -1.0260,  0.5671]]) torch.Size([2, 8])


<center> 
<img src="./img/lnnp2_resize1.png" alt="Операции изменения размера матриц" style="width: 300px;"/><br/>
    <b>Операции изменения размера матриц</b>    
</center> 

In [30]:
x1 = torch.rand(2,3)
print(x1)
y1 = torch.rand(2,3)
print(y1)

tensor([[0.6639, 0.0077, 0.9804],
        [0.4994, 0.5609, 0.4678]])
tensor([[0.1174, 0.6460, 0.3163],
        [0.5646, 0.6701, 0.0831]])


In [31]:
# Конкатенация (concatenation):

print('x1', x1, x1.size())
print('y1', y1, y1.size())

# Concatenates 2 tensors on zeroth dimension:
concat1 = torch.cat((x1, y1))
print(concat1, concat1.size())         

# Concatenates 2 tensors on zeroth dimension
x = torch.rand(2,3)
concat2 = torch.cat((x1, y1), dim=0)
print(concat2, concat2.size()) 

# Concatenates 2 tensors on first dimension
x = torch.rand(2,3)
concat3 = torch.cat((x1, y1), dim=1)
print(concat3, concat3.size())       

x1 tensor([[0.6639, 0.0077, 0.9804],
        [0.4994, 0.5609, 0.4678]]) torch.Size([2, 3])
y1 tensor([[0.1174, 0.6460, 0.3163],
        [0.5646, 0.6701, 0.0831]]) torch.Size([2, 3])
tensor([[0.6639, 0.0077, 0.9804],
        [0.4994, 0.5609, 0.4678],
        [0.1174, 0.6460, 0.3163],
        [0.5646, 0.6701, 0.0831]]) torch.Size([4, 3])
tensor([[0.6639, 0.0077, 0.9804],
        [0.4994, 0.5609, 0.4678],
        [0.1174, 0.6460, 0.3163],
        [0.5646, 0.6701, 0.0831]]) torch.Size([4, 3])
tensor([[0.6639, 0.0077, 0.9804, 0.1174, 0.6460, 0.3163],
        [0.4994, 0.5609, 0.4678, 0.5646, 0.6701, 0.0831]]) torch.Size([2, 6])


In [32]:
# Разбиение тензора (split): 
print(x1)

splitted1 = x1.split(split_size=1, dim=0)
print(splitted1, splitted1[0].size())       # 2 tensors of 2x2 and 1x2 size

splitted2 = x1.split(split_size=2, dim=1)
print(splitted2[0], splitted2[0].size(), '\n', splitted2[1], splitted2[1].size())       # 2 tensors of 2x2 and 1x2 size

tensor([[0.6639, 0.0077, 0.9804],
        [0.4994, 0.5609, 0.4678]])
(tensor([[0.6639, 0.0077, 0.9804]]), tensor([[0.4994, 0.5609, 0.4678]])) torch.Size([1, 3])
tensor([[0.6639, 0.0077],
        [0.4994, 0.5609]]) torch.Size([2, 2]) 
 tensor([[0.9804],
        [0.4678]]) torch.Size([2, 1])


In [33]:
# stack:
print(x1)
print(y1)

stacked1 = torch.stack((x1, y1), dim=0)
print(stacked1, stacked1.size()) # возвращает тензор: 2(в результате stak!) x 2 x 3 

tensor([[0.6639, 0.0077, 0.9804],
        [0.4994, 0.5609, 0.4678]])
tensor([[0.1174, 0.6460, 0.3163],
        [0.5646, 0.6701, 0.0831]])
tensor([[[0.6639, 0.0077, 0.9804],
         [0.4994, 0.5609, 0.4678]],

        [[0.1174, 0.6460, 0.3163],
         [0.5646, 0.6701, 0.0831]]]) torch.Size([2, 2, 3])


In [34]:
stacked2 = torch.stack((x1, y1), dim=1)
print(stacked2, stacked2.size()) # возвращает тензор: 2 x 2(в результате stak!) x 3 

tensor([[[0.6639, 0.0077, 0.9804],
         [0.1174, 0.6460, 0.3163]],

        [[0.4994, 0.5609, 0.4678],
         [0.5646, 0.6701, 0.0831]]]) torch.Size([2, 2, 3])


In [35]:
#sqeeze and unsqueeze
x2 = torch.rand(3, 2, 1) # a tensor of size 3x2x1
print(x2, x2.size())
squeezed1 = x2.squeeze()
print(squeezed1, squeezed1.size())  # remove the 1 sized dimension

tensor([[[0.8924],
         [0.1753]],

        [[0.4132],
         [0.0358]],

        [[0.8070],
         [0.5193]]]) torch.Size([3, 2, 1])
tensor([[0.8924, 0.1753],
        [0.4132, 0.0358],
        [0.8070, 0.5193]]) torch.Size([3, 2])


In [36]:
x3 = torch.rand(3)
print(x3)

with_fake_dimension1 = x3.unsqueeze(0)
print(with_fake_dimension1, with_fake_dimension1.size()) # added a fake zeroth dimensionz 

with_fake_dimension2 = x3.unsqueeze(1)
print(with_fake_dimension2, with_fake_dimension2.size()) # added a fake zeroth dimensionz 

tensor([0.7489, 0.6993, 0.9901])
tensor([[0.7489, 0.6993, 0.9901]]) torch.Size([1, 3])
tensor([[0.7489],
        [0.6993],
        [0.9901]]) torch.Size([3, 1])


In [37]:
# Распространение (broadcasting) - так же как в NumPy:

t1 = torch.arange(1.0, 5.0)
t3 = torch.arange(0.0, 3.0)
print(t1, t3)
tm = t1.ger(t3)
print(tm, tm.size())

tensor([1., 2., 3., 4.]) tensor([0., 1., 2.])
tensor([[0., 1., 2.],
        [0., 2., 4.],
        [0., 3., 6.],
        [0., 4., 8.]]) torch.Size([4, 3])


In [38]:
t1 * tm

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [39]:
t1.size(), tm.size()

(torch.Size([4]), torch.Size([4, 3]))

In [40]:
print(t1.unsqueeze(1))
print(tm)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[0., 1., 2.],
        [0., 2., 4.],
        [0., 3., 6.],
        [0., 4., 8.]])


In [41]:
t1.unsqueeze(1) * tm

tensor([[ 0.,  1.,  2.],
        [ 0.,  4.,  8.],
        [ 0.,  9., 18.],
        [ 0., 16., 32.]])

In [42]:
t1.unsqueeze(1).size(), tm.size()

(torch.Size([4, 1]), torch.Size([4, 3]))

#### Операции агрегации: <a class="anchor" id="агрегации"></a>
* [к оглавлению](#разделы)

In [43]:
mat = torch.tensor(
        [[0., 1., 2.],
        [0., 2., 4.],
        [0., 3., 6.],
        [0., 4., 8.]])

# суммирование по всем элементам:
mat.sum()

tensor(30.)

In [44]:
# суммирование по оси 0:
mat.sum(dim=0)

tensor([ 0., 10., 20.])

In [45]:
# суммирование по оси 1:
mat.sum(dim=1)

tensor([ 3.,  6.,  9., 12.])

In [46]:
# получение среднего значения:

print(mat.mean())
print(mat.mean(dim=0))
print(mat.mean(dim=1))

tensor(2.5000)
tensor([0.0000, 2.5000, 5.0000])
tensor([1., 2., 3., 4.])


#### Матричные операции: <a class="anchor" id="матричные"></a>
* [к оглавлению](#разделы)

In [47]:
# Умножение (поэлементное!):

x = torch.rand(2, 2)
print(f'x:\n {x}\n')
y = torch.rand(2, 2)
print(f'y:\n {y}\n')

z = x * y
print(f'z = torch.mul(x,y):\n {z}\n')
z = torch.mul(x,y)
print(f'z = torch.mul(x,y):\n {z}\n')

x:
 tensor([[0.2199, 0.1196],
        [0.7685, 0.0695]])

y:
 tensor([[0.5980, 0.3176],
        [0.5966, 0.8181]])

z = torch.mul(x,y):
 tensor([[0.1315, 0.0380],
        [0.4584, 0.0568]])

z = torch.mul(x,y):
 tensor([[0.1315, 0.0380],
        [0.4584, 0.0568]])



In [48]:
# Умножение матрицы на вектор:

# torch.mv(input, vec, out=None) → Tensor
# Performs a matrix-vector product of the matrix input and the vector vec.
# If input is a (n \times m)(n×m) tensor, vec is a 1-D tensor of size mm , out will be 1-D of size nn .

mat = torch.randn(2, 3)
print(mat, mat.size())
vec = torch.randn(3)
print(vec, vec.size())
res = torch.mv(mat, vec)
print(res, res.size())

tensor([[ 0.9493,  1.1510, -1.6558],
        [-0.0850,  2.3649, -0.3201]]) torch.Size([2, 3])
tensor([-1.1828, -1.0324, -0.4864]) torch.Size([3])
tensor([-1.5057, -2.1853]) torch.Size([2])


In [49]:
# Умножение матрицы на матрицу:

# torch.mm(input, mat2, out=None) → Tensor
# Performs a matrix multiplication of the matrices input and mat2.
# If input is a (n×m) tensor, mat2 is a (m×p) tensor, out will be a (n×p) tensor.

mat1 = torch.randn(2, 3)
print(mat1, mat1.size())
mat2 = torch.randn(3, 3)
print(mat2, mat2.size())
res = torch.mm(mat1, mat2)
print(res, res.size())

tensor([[-0.4345, -0.1421, -0.8577],
        [ 0.1780, -0.5208, -0.1037]]) torch.Size([2, 3])
tensor([[ 1.7205,  0.1873,  0.1930],
        [-0.9793,  0.5428, -0.9690],
        [-0.7717, -0.0712, -2.0188]]) torch.Size([3, 3])
tensor([[ 0.0535, -0.0974,  1.7855],
        [ 0.8964, -0.2420,  0.7484]]) torch.Size([2, 3])


In [50]:
mat1.mm(mat2)

tensor([[ 0.0535, -0.0974,  1.7855],
        [ 0.8964, -0.2420,  0.7484]])

In [51]:
# Outer product of 2 vectors
vec1 = torch.arange(1, 4)    # Size 3
print(vec1, vec1.size())
vec2 = torch.arange(1, 3)    # Size 2
print(vec2, vec2.size())
res = torch.ger(vec1, vec2) # vec1 - рассматривается как вектор-столбец; vec2 - рассматривается как вектор-строка
print(res, res.size()) # Size 3x2

tensor([1, 2, 3]) torch.Size([3])
tensor([1, 2]) torch.Size([2])
tensor([[1, 2],
        [2, 4],
        [3, 6]]) torch.Size([3, 2])


In [52]:
vec1.ger(vec2)

tensor([[1, 2],
        [2, 4],
        [3, 6]])

__Функция matmul__

* Matrix product of two tensors: `torch.matmul(input, other, out=None)` → Tensor
* The behavior depends on the dimensionality of the tensors as follows:
    * If __both tensors are 1-dimensional__, the __dot product (scalar) is returned__.
    * If __both arguments are 2-dimensional__, the __matrix-matrix product is returned__.
    * If the __first argument is 1-dimensional and the second argument is 2-dimensional__, a 1 is prepended to its dimension for the purpose of the matrix multiply. After the matrix multiply, the prepended dimension is removed.
    * If the __first argument is 2-dimensional and the second argument is 1-dimensional__, the matrix-vector product is returned.
    * If __both arguments are at least 1-dimensional and at least one argument is N-dimensional (where N > 2)__, then a batched matrix multiply is returned. If the first argument is 1-dimensional, a 1 is prepended to its dimension for the purpose of the batched matrix multiply and removed after. If the second argument is 1-dimensional, a 1 is appended to its dimension for the purpose of the batched matrix multiple and removed after. The non-matrix (i.e. batch) dimensions are broadcasted (and thus must be broadcastable). For example, if input is a $j \times 1 \times n \times m$ tensor and other is a $k \times m \times p$ tensor, out will be an $j \times k \times n \times p$ tensor.

In [53]:
torch.arange(4)

tensor([0, 1, 2, 3])

In [54]:
torch.arange(3*4).view(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [55]:
# vector x vector
tensor1 = torch.randn(3)
print(tensor1, tensor1.size())
tensor2 = torch.randn(3)
print(tensor2, tensor2.size())
res = torch.matmul(tensor1, tensor2)
print(res, res.size()) # результат: скаляр

tensor([-0.3119, -1.0818, -0.4820]) torch.Size([3])
tensor([ 1.4567, -1.0361, -0.2431]) torch.Size([3])
tensor(0.7835) torch.Size([])


In [56]:
# Вызов функции matmul можно выполнять с помощью оператора @:
tensor1 @ tensor2

tensor(0.7835)

In [57]:
# vector x matrix 
tensor1 = torch.arange(3*4).view(3, 4)
print(tensor1, tensor1.size())
tensor2 = torch.arange(3)
print(tensor2, tensor2.size())

res = torch.matmul(tensor2, tensor1)
print(res, res.size())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) torch.Size([3, 4])
tensor([0, 1, 2]) torch.Size([3])
tensor([20, 23, 26, 29]) torch.Size([4])


In [58]:
# или:
tensor2 @ tensor1

tensor([20, 23, 26, 29])

In [59]:
# matrix x vector
tensor1 = torch.arange(3*4).view(3, 4)
print(tensor1, tensor1.size())
tensor2 = torch.arange(4)
print(tensor2, tensor2.size())

res = torch.matmul(tensor1, tensor2)
print(res, res.size())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) torch.Size([3, 4])
tensor([0, 1, 2, 3]) torch.Size([4])
tensor([14, 38, 62]) torch.Size([3])


In [60]:
tensor1 @ tensor2

tensor([14, 38, 62])

In [61]:
# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
print(tensor1, tensor1.size(), '\n------------')
tensor2 = torch.randn(4)
print(tensor2, tensor2.size(), '\n------------')
res = torch.matmul(tensor1, tensor2)
print(res, res.size())

tensor([[[-0.0855,  0.1109, -1.1968,  0.4364],
         [-1.1133,  0.1061,  0.3969, -0.3609],
         [ 1.1275,  0.8102, -1.9461,  0.1830]],

        [[-1.3840,  0.9182,  0.3561, -0.5380],
         [-1.7731, -1.4110,  1.9301, -1.2784],
         [ 0.4491, -0.1984, -1.4689,  0.0231]],

        [[ 1.3571,  0.5333, -0.1727,  0.2302],
         [ 0.6805, -1.6450,  2.3968, -0.8665],
         [-0.3385, -1.3563, -0.3013, -0.3415]],

        [[-1.1634,  0.5276,  0.6327, -0.9683],
         [-0.4906, -0.6952,  0.7545,  0.8810],
         [ 0.4595, -0.3860,  1.3281,  0.0822]],

        [[ 0.6454,  0.3294,  0.1009,  0.5281],
         [ 0.0773, -0.1222,  1.0941, -1.2498],
         [-0.5284,  1.3452,  0.9620,  0.8696]],

        [[ 0.0075,  1.9015, -1.9170,  0.0950],
         [ 0.9659,  2.0283, -0.0033, -0.1204],
         [ 0.5548, -0.6155, -0.6774, -0.1425]],

        [[-0.9337,  1.5523,  1.3298, -0.7942],
         [ 0.0633, -0.4587, -1.4576,  0.9234],
         [-1.0258,  0.4962, -1.4273, -0.8872]],


In [62]:
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
print(tensor1.size(), '\n------------')
tensor2 = torch.randn(10, 4, 5)
print(tensor2.size(), '\n------------')
res = torch.matmul(tensor1, tensor2)
print(res.size())

torch.Size([10, 3, 4]) 
------------
torch.Size([10, 4, 5]) 
------------
torch.Size([10, 3, 5])


In [63]:
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
print(tensor1.size(), '\n------------')
tensor2 = torch.randn(4, 5)
print(tensor2, tensor2.size(), '\n------------')
res = torch.matmul(tensor1, tensor2)
print(res.size())

torch.Size([10, 3, 4]) 
------------
tensor([[ 0.8469, -0.4879,  0.4446, -1.4072, -0.2130],
        [-0.7078, -0.4156, -0.4201,  0.9509, -0.2736],
        [ 0.2610,  0.3725, -1.0016,  2.5182, -0.8951],
        [ 0.3494,  1.9036,  1.0719,  1.1308, -0.3430]]) torch.Size([4, 5]) 
------------
torch.Size([10, 3, 5])


---
# Спасибо за внимание!

---
### Технический раздел:

 * И Введение в искусственные нейронные сети
     * Базовые понятия и история
 * И Машинное обучение и концепция глубокого обучения
 * И Почему глубокое обучение начало приносить плоды и активно использоваться только после 2010 г?
     * Производительность оборудования
     * Доступность наборов данных и тестов
     * Алгоритмические достижения в области глубокого обучения
         * Улчшенные подходы к регуляризации
         * Улучшенные схемы инициализации весов
         * (повтор) Усовершенствованные методы градиентного супска
         

* Обратное распространение ошибки
 * Оптимизация
     * Стохастический градиентный спуск
     * Усовершенствованные методы градиентного супска
* Введение в PyTorch

<br/> next <em class="qs"></em> qs line 
<br/> next <em class="an"></em> an line 
<br/> next <em class="nt"></em> an line 
<br/> next <em class="df"></em> df line 
<br/> next <em class="ex"></em> ex line 
<br/> next <em class="pl"></em> pl line 
<br/> next <em class="mn"></em> mn line 
<br/> next <em class="plmn"></em> plmn line 
<br/> next <em class="hn"></em> hn line 