# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [10]:
import numpy as np
arr = np.random.uniform(0,20,(4,7))
arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(np.round(arr,4))

[[0.     0.9807 0.2739 0.4294 0.4719 0.7546 0.0243]
 [0.3277 0.6144 0.6601 0.4245 0.7118 1.     0.5472]
 [0.3719 0.5503 0.3076 0.3599 0.4763 0.4055 0.7741]
 [0.5187 0.517  0.856  0.4429 0.9488 0.7049 0.6426]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [33]:
import numpy as np
A = np.random.randint(0,10,(8,10))
q = np.argmin(np.sum(A, axis = 1))
print(q, A[q,])


3 [4 2 0 7 1 2 1 9 2 2]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [1]:
import numpy as np
A = np.array([2,4,6,8,10])
B = np.array([1,3,5,7,9])
dist = np.linalg.norm(A-B)
print(round(dist,3))


2.236


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [7]:
import numpy as np
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
X = np.matmul(np.matmul(np.linalg.inv(A),(C * -1)), np.linalg.inv(B))
print(np.round(X))

[[ 1.  0.]
 [-2.  1.]
 [ 3. -4.]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [8]:
import numpy as np
arr = np.loadtxt(r"minutes_n_ingredients.csv", delimiter=';', dtype=np.int32)
print(arr[:5,])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [40]:
import numpy as np
arr = np.loadtxt(r"C:\Users\222690\Downloads\minutes_n_ingredients.csv", delimiter=';', dtype=np.int32)
print(np.mean(arr[:,1]), np.min(arr[:,1]), np.max(arr[:,1]), np.median(arr[:,1]))
print(np.mean(arr[:,2]), np.min(arr[:,2]), np.max(arr[:,2]), np.median(arr[:,2]))

21601.00169 0 2147483647 40.0
9.05528 1 39 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [30]:
import numpy as np
arr = np.loadtxt(r"C:\Users\222690\Downloads\minutes_n_ingredients.csv", delimiter=';', dtype=np.int32)
print(np.quantile(arr[:,1],.75))

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [42]:
import numpy as np
arr = np.loadtxt(r"C:\Users\222690\Downloads\minutes_n_ingredients.csv", delimiter=';', dtype=np.int32)
print (np.count_nonzero(arr[:,1] == 0))
arr[arr[:,1] == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [26]:
import numpy as np
arr = np.loadtxt(r"C:\Users\222690\Downloads\minutes_n_ingredients.csv", delimiter=';', dtype=np.int32)
print(len(np.unique(arr[:,0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [32]:
import numpy as np
arr = np.loadtxt(r"C:\Users\222690\Downloads\minutes_n_ingredients.csv", delimiter=';', dtype=np.int32)
print(np.unique(arr[:,2]))
print(len(np.unique(arr[:,2])))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [9]:
short_cut = arr[np.where(arr[:, 2] <= 5)[0]]
short_cut, short_cut.shape

(array([[446597,     15,      5],
        [204134,      5,      3],
        [ 25623,      6,      4],
        ...,
        [ 52088,     60,      5],
        [128811,     15,      4],
        [370915,      5,      4]]),
 (17262, 3))

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [10]:
np.max(arr[:, 2]/arr[:, 1]), arr[:, 2]/arr[:, 1]

C:\Users\alexm\AppData\Local\Temp\ipykernel_179760\1091088505.py:1: RuntimeWarning: divide by zero encountered in divide
  np.max(arr[:, 2]/arr[:, 1]), arr[:, 2]/arr[:, 1]


(inf,
 array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.1       ]))

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [11]:
sorted_indices = np.argsort(arr[:, 1])[-100:]
sorted_array = arr[sorted_indices]
sorted_array[:, 2].mean()

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [66]:
import numpy as np
arr = np.loadtxt(r"C:\Users\222690\Downloads\minutes_n_ingredients.csv", delimiter=';', dtype=np.int32)
arr2 = np.random.choice(arr.shape[0], size = 10)
print(arr[arr2,])


[[258266     40      9]
 [232473      5      4]
 [189821     14     12]
 [305350     20     14]
 [228937     40      5]
 [223870    190      8]
 [367975     55      9]
 [431865     45     10]
 [205331     12     15]
 [520826     30      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [13]:
str(len(np.where(arr[:, 2] < arr[:, 2].mean())[0])/arr.shape[0]*100) + "%"

'58.802%'

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [14]:
good_recepts = np.zeros((arr.shape[0], 4), dtype=int) # Создаём пустой датасет
good_recepts[:, :3] = arr # Заполняем первые 3
good_recepts[np.where((arr[:, 2] <= 5) & (arr[:, 1] <= 20)), 3] = 1
good_recepts

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [15]:
str(sum(good_recepts[:, 3])/arr.shape[0]*100) + '%'

'9.552%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [16]:
short_recipes = arr[arr[:, 1] < 10]
standard_recipes = arr[(arr[:, 1] >= 10) & (arr[:, 1] < 20)]
long_recipes = arr[arr[:, 1] >= 20]

max_length = min(len(short_recipes), len(standard_recipes), len(long_recipes))

three_dimensional_array = np.zeros((3, max_length, 3), dtype=int)

three_dimensional_array[0, :max_length, :] = short_recipes[:max_length]
three_dimensional_array[1, :max_length, :] = standard_recipes[:max_length]
three_dimensional_array[2, :max_length, :] = long_recipes[:max_length]

three_dimensional_array.shape, three_dimensional_array

((3, 7588, 3),
 array([[[ 67660,      5,      6],
         [366174,      7,      9],
         [204134,      5,      3],
         ...,
         [420725,      5,      3],
         [  4747,      0,      9],
         [370915,      5,      4]],
 
        [[ 94746,     10,      6],
         [ 33941,     18,      9],
         [446597,     15,      5],
         ...,
         [  9831,     15,      7],
         [335859,     12,     14],
         [256812,     10,      3]],
 
        [[127244,     60,     16],
         [ 23891,     25,      7],
         [157911,     60,     14],
         ...,
         [168901,     25,      7],
         [392339,     35,     13],
         [206732,     45,     10]]]))